version: "1" # required to adjust maintainability checks

# A lot of rules will be very lose because React hooks is just like that

checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 20
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 100
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 6
  similar-code:
    config:
      threshold: 60
      count_threshold: 3
  identical-code:
    config:
      threshold: 30
      count_threshold: 2

exclude_patterns:
  - "src/serviceWorker.ts"
