version: "1" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 300
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 15
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 6
  return-statements:
    config:
      threshold: 6
  similar-code:
    enabled: true
  identical-code:
    enabled: true

exclude_patterns:
  - "src/serviceWorker.ts"
