name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install deps
        run: yarn --frozen-lockfile

      - name: lint
        run: yarn lint -CI

      - name: check with prettier
        run: yarn prettier . --check

      - name: build
        run: yarn build
        env:
          CI: false
