name: build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: yarn --frozen-lockfile

    - name: lint
      run: yarn lint

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: yarn --frozen-lockfile

    - name: build
      run: yarn build
      env:
        CI: false
